/**
 * AI Proposal Generation Domain Types (ORDX-018A)
 *
 * Defines structured types for AI-generated proposal content.
 * These types represent the output shape from the AI generation layer.
 */

/**
 * Executive summary section of the generated proposal.
 * Provides a high-level overview of the project and recommendations.
 */
export interface ExecutiveSummary {
  /** Brief overview of the project scope */
  overview: string;
  /** Key value propositions for the client */
  valueProposition: string;
  /** Primary recommendation summary */
  recommendation: string;
}

/**
 * Project understanding section demonstrating comprehension of client needs.
 */
export interface ProjectUnderstanding {
  /** Understanding of client's business context */
  businessContext: string;
  /** Identified project objectives */
  objectives: string[];
  /** Understanding of operational needs and context */
  operationalNeeds: string;
  /** Key constraints identified */
  constraints: string[];
}

/**
 * Design direction recommendations.
 */
export interface ProposedApproach {
  /** Overall recommended approach summary */
  approachSummary: string;
  /** Recommended workstreams or service components */
  workstreams: string[];
  /** Suggested engagement model */
  engagementModel: string;
  /** Recommended delivery approach */
  deliveryApproach: string;
  /** Tools, capabilities, or enablement elements */
  capabilityEnablers: string[];
}

/**
 * Individual spatial planning recommendation.
 */
export interface SpatialRecommendation {
  /** Area/zone name */
  area: string;
  /** Specific recommendation */
  recommendation: string;
  /** Rationale for the recommendation */
  rationale: string;
}

/**
 * Spatial planning recommendations section.
 */
export interface ScopeRecommendations {
  /** Overall scope strategy */
  overallStrategy: string;
  /** Specific workstream or scope recommendations */
  areaRecommendations: SpatialRecommendation[];
  /** Cross-functional coordination considerations */
  circulationFlow: string;
  /** Flexibility and future expansion considerations */
  flexibilityConsiderations: string;
}

/**
 * Budget narrative explaining the cost structure.
 */
export interface BudgetNarrative {
  /** Overview of budget allocation */
  overview: string;
  /** Major cost categories and their rationale */
  costBreakdown: string[];
  /** Value engineering opportunities */
  valueEngineeringOptions: string[];
  /** Budget confidence explanation */
  confidenceExplanation: string;
}

/**
 * Timeline narrative explaining the project schedule.
 */
export interface TimelineNarrative {
  /** Overview of project phases */
  overview: string;
  /** Key milestones */
  milestones: string[];
  /** Critical path items */
  criticalPath: string[];
  /** Schedule confidence explanation */
  confidenceExplanation: string;
}

/**
 * Risk or assumption item.
 */
export interface RiskOrAssumption {
  /** Description of the risk or assumption */
  description: string;
  /** Impact level: low, medium, high */
  impact: "low" | "medium" | "high";
  /** Mitigation strategy (for risks) or validation approach (for assumptions) */
  mitigationOrValidation: string;
}

/**
 * Risks and assumptions section.
 */
export interface RisksAndAssumptions {
  /** Identified risks */
  risks: RiskOrAssumption[];
  /** Working assumptions */
  assumptions: RiskOrAssumption[];
}

/**
 * Recommended next steps for the client.
 */
export interface RecommendedNextSteps {
  /** Immediate actions */
  immediate: string[];
  /** Short-term actions */
  shortTerm: string[];
  /** Decision points */
  decisionPoints: string[];
}

/**
 * Complete structured proposal content generated by AI.
 * This is the primary output type from the AI generation layer.
 */
export interface GeneratedProposalContent {
  /** Executive summary section */
  executiveSummary: ExecutiveSummary;
  /** Project understanding section */
  projectUnderstanding: ProjectUnderstanding;
  /** Proposed approach section */
  proposedApproach: ProposedApproach;
  /** Scope recommendations */
  scopeRecommendations: ScopeRecommendations;
  /** Budget narrative */
  budgetNarrative: BudgetNarrative;
  /** Timeline narrative */
  timelineNarrative: TimelineNarrative;
  /** Risks and assumptions */
  risksAndAssumptions: RisksAndAssumptions;
  /** Recommended next steps */
  recommendedNextSteps: RecommendedNextSteps;
  /** Generation metadata */
  metadata: {
    /** Timestamp of generation */
    generatedAt: string;
    /** Model used for generation */
    modelUsed: string;
    /** Provider identifier */
    provider: string;
    /** Token usage if available */
    tokenUsage?: {
      promptTokens: number;
      completionTokens: number;
      totalTokens: number;
    };
  };
}

/**
 * Input context for proposal generation.
 * Combines project data with estimation results.
 */
export interface ProposalGenerationInput {
  /** Project/proposal context */
  projectContext: {
    /** Proposal title */
    title: string;
    /** Client name */
    clientName: string;
    /** Contact name */
    contactName: string;
    /** Industry sector */
    industry: string;
    /** Project type name */
    projectTypeName: string;
    /** Style option name */
    styleOptionName: string;
    /** Project scope items */
    scope: string[];
  };
  /** Estimation results (pre-calculated, not computed by AI) */
  estimationContext: {
    /** Relative scope size */
    scopeSize: number;
    /** Delivery complexity on a 1-5 scale */
    complexityLevel: number;
    /** Stakeholder or coordination track count */
    stakeholderCount: number;
    /** Included options */
    includedOptions: string[];
    /** Budget range */
    budgetRange: {
      min: number;
      max: number;
      currency: string;
    };
    /** Timeline range */
    timelineRange: {
      minWeeks: number;
      maxWeeks: number;
    };
    /** Style multiplier applied */
    styleMultiplier: number;
    /** Whether accelerated delivery is required */
    isExpeditedDelivery: boolean;
  };
  /** Optional service modules selected */
  serviceModules: {
    includeDiscoveryWorkshop: boolean;
    includeTrainingEnablement: boolean;
    includeImplementationSupport: boolean;
    includeCustomDeliverables: boolean;
    includeAutomationIntegration: boolean;
    includeComplianceReview: boolean;
  };
  /** Optional generation hints */
  domainContext?: {
    /** Preferred delivery or collaboration preferences */
    deliveryPreferences?: string[];
    /** Reference principles or standards */
    referenceGuidelines?: string;
    /** Special requirements */
    specialRequirements?: string[];
  };
}

/**
 * Provider-agnostic interface for AI generation providers.
 * Allows swapping between Gemini, OpenAI, or mock implementations.
 */
export interface AIGenerationProvider {
  /** Provider identifier */
  readonly providerId: string;

  /** Generate proposal content from input */
  generateProposalContent(
    input: ProposalGenerationInput
  ): Promise<GeneratedProposalContent>;

  /** Check if provider is available and configured */
  isAvailable(): Promise<boolean>;
}

/**
 * Configuration for AI generation.
 */
export interface AIGenerationConfig {
  /** Preferred provider to use */
  provider: "gemini" | "mock";
  /** Model identifier (provider-specific) */
  model?: string;
  /** Maximum tokens for completion */
  maxTokens?: number;
  /** Temperature for generation */
  temperature?: number;
  /** Whether to use mock fallback on error */
  useMockFallback?: boolean;
}
